<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends CachedEntityRepository
{
    protected $lifetime = null; // ex. 3600
    protected $alias = null;    // ex. _books_

}
